# Generated by Django 4.1 on 2023-09-11 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('from_type', models.CharField(choices=[('CONSTANT', 'Constant'), ('STATUS', 'Status'), ('PROJECT_TYPE', 'Project Type')], max_length=100)),
                ('value_str', models.CharField(max_length=100)),
                ('value_int', models.IntegerField(default=0)),
                ('value_bool', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('SUB_TASK', 'Subtask'), ('TASK', 'Task'), ('GROUP_TASK', 'Group task'), ('MILESTONE', 'Milestone Type'), ('PHASE', 'Phase')], max_length=100)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('reported_date', models.DateTimeField(verbose_name='reported date')),
                ('actual_start_date', models.DateTimeField(verbose_name='actual start date')),
                ('actual_end_date', models.DateTimeField(verbose_name='actual end date')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.IntegerField(default=0)),
                ('gravity', models.IntegerField(default=0)),
                ('criticality', models.IntegerField(default=0)),
                ('value_int', models.IntegerField(default=0)),
                ('value_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.code')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('date_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.grouptask')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.priority')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reported_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.code')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('date_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.priority')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask_reported_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.code')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.priority')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.project')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.phase')),
            ],
        ),
        migrations.AddField(
            model_name='grouptask',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.phase'),
        ),
    ]
