# Generated by Django 4.1 on 2023-12-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='teams',
            new_name='groups',
        ),
    ]
