# Generated by Django 4.1 on 2023-09-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='priority',
            name='value_str',
            field=models.CharField(choices=[('LOW', 'Low'), ('LOW_MEDIUM', 'Low Medium'), ('MEDIUM', 'Medium'), ('MEDIUM_HIGH', 'Medium High'), ('HIGH', 'High')], max_length=100),
        ),
        migrations.AddField(
            model_name='subtask',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tag'),
        ),
    ]
