# Generated by Django 4.1 on 2023-12-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_teams_project_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='PROJECT', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_tasks', to='tasks.tasklist'),
        ),
    ]
