# Generated by Django 4.1 on 2023-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptask',
            name='tags',
            field=models.ManyToManyField(related_name='tag_grouptasks', to='tasks.tag'),
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='tag',
        ),
        migrations.AddField(
            model_name='subtask',
            name='tag',
            field=models.ManyToManyField(related_name='tag_subtasks', to='tasks.tag'),
        ),
    ]
