# Generated by Django 4.1 on 2023-10-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_grouptask_tags_remove_subtask_tag_subtask_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='tag',
            new_name='tags',
        ),
    ]
