# Generated by Django 4.1 on 2023-10-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0006_alter_task_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphasetemplatelink',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectphasetemplatelink',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='projectphasetemplatelink',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectphasetemplatelink',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ManyToManyField(related_name='projects', to='tasks.phase'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='ProjectGroupLink',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseTemplateLink',
        ),
    ]
