# Generated by Django 4.1 on 2023-10-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_projectphasetemplatelink_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='phase',
            new_name='phases',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='team',
            new_name='teams',
        ),
    ]
