# Generated by Django 4.1 on 2023-10-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_phase_project_phases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='date_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='date_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='date_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.datedetail'),
        ),
    ]
