# Generated by Django 4.1 on 2023-10-05 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_project_phases_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('phases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.phase')),
                ('templates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.template')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
