# Generated by Django 4.1 on 2023-10-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_templatephase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='phases',
        ),
        migrations.AddField(
            model_name='template',
            name='phases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='tasks.phase'),
        ),
    ]
