# Generated by Django 4.1 on 2023-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_phases_templatephase_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_phases',
            field=models.ManyToManyField(related_name='projects', to='tasks.templatephase'),
        ),
        migrations.AddField(
            model_name='template',
            name='phases',
            field=models.ManyToManyField(through='tasks.TemplatePhase', to='tasks.phase'),
        ),
    ]
