# Generated by Django 4.1 on 2023-10-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_project_template_phases_template_phases'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='templatephase',
            table='tasks_template_phase',
        ),
    ]
