# Generated by Django 4.1 on 2023-10-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_projecttemplatephase_remove_project_template_phases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='templates',
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tasks.template'),
        ),
        migrations.AlterModelTable(
            name='projecttemplatephase',
            table='tasks_project_template_phases',
        ),
    ]
