# Generated by Django 4.1 on 2023-10-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_project_templates_project_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplatephase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.project', unique=True),
        ),
    ]
