# Generated by Django 4.1 on 2023-10-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_datedetail_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='tasks.datedetail'),
        ),
    ]
