# Generated by Django 4.1 on 2023-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_task_date_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='from_type',
            field=models.CharField(choices=[('CONSTANT', 'Constant'), ('STATUS', 'Status')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
